apiVersion: v1
kind: Service
metadata:
  name: noteport30000-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: guestbook-ui
  type: NodePort
