apiVersion: v1
kind: Service
metadata:
  name: noteport30001-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: guestbook-ui
  type: NodePort
